#import "../../../utils.typ": table_d66

#pagebreak()
== Tabelle Avventura

La città scrive le sue storie col sangue. Tira sulla tabella qui sotto quando hai bisogno di un aggancio narrativo. Questi semi sono punti di partenza, non copioni. Stravolgili. Rendili tuoi. Lasciali marcire.

#table_d66(
  (
    [Hanno pescato un sarcofago dal porto—pietra più antica della città stessa. L'università lo riceverà stasera. Vampiri del sangue stanno strisciando fuori dalle tane, disperati per fermarlo. Cosa è sigillato all'interno? E perché spaventa cose che non si spaventano facilmente?],
    [La luna piena sanguina rosso stanotte. Ululati echeggiano per le strade—non ululati di lupo, qualcosa di più antico. Figure incappucciate si radunano nei vicoli, cantilenando in una lingua che ti fa dolere i denti. I lupi mannari sono chiusi dentro, terrorizzati. Che rituale è questo? E cosa succede quando sarà completo?],
    [L'FSB ha fatto irruzione in un nido di Red Hood—ultimo piano di un magazzino sul lungomare. Quando hanno sfondato la porta, il posto era sventrato. Vuoto. Sangue ancora fresco sui muri. Un'agente non vuole lasciar perdere. Sta facendo domande. Domande pericolose. Cosa hanno lasciato indietro i vampiri? E perché è così sicura che torneranno?],
    [La Mano ha una talpa nel distretto. Ora la sua copertura è saltata ed è alla tua porta, sanguinante e disperato. Non sanno cosa sei veramente. Perché si fidano di te? E quale segreto stai nascondendo che potrebbe farvi uccidere entrambi?],
    [Sei a capo di una congrega di streghe rinnegate, in fuga per le vostre vite. La città è il vostro ultimo rifugio—un posto dove sparire nelle crepe. Chi vi sta dando la caccia? Cosa avete fatto per meritarvi una condanna a morte? E quanto tempo prima che vi trovino qui?],
    [Il cadavere del sindaco è riverso sulla sua scrivania, gola squarciata, sangue accumulato sul mogano importato. Segni di zanne. Nessun dubbio su cosa abbia fatto questo. Qualcuno sta già lavorando per insabbiare la storia—pulendo la scena, comprando il silenzio. Chi lo sta coprendo? E li stai aiutando o stai bruciando tutto?],
    [Tuo fratello ti trascina da un motel all'altro, inseguendo un lavoro che non vuole spiegare. "Caccia", dice. Lo curi quando torna giorni dopo, sanguinante, mezzo morto. Poi se ne va di nuovo. È passato un mese questa volta. Niente chiamate. Niente messaggi. Non puoi andare dalla polizia. Perché no? Cosa trovi quando cerchi tra le sue cose? E perché ha dovuto portarti con sé?],
    [Sei ubriaco, inciampando tra i vicoli con la tua banda. Trovi il tuo amico premuto contro un cassonetto, una ragazza sopra di lui. Tranne che non lo sta baciando—si sta nutrendo. Zanne profonde nella sua gola. Sangue ovunque. Lui si sta ancora contorcendo. Cosa fai?],
    [Stanotte è la notte. Il branco finalmente ti lascia entrare. Hai aspettato anni per questo—per sapere cosa succede sotto la luna piena, per capire cosa è veramente la tua famiglia. Il rituale sta iniziando. La luna sta sorgendo. E stai per scoprire se sei abbastanza forte da sopravvivere.],
    [Lavori al turno di notte all'obitorio. Silenzioso. Freddo. Poi senti metallo che raschia—un cassetto che si apre. Uno dei cadaveri si siede, fa oscillare le gambe oltre il bordo e punta una pistola al tuo petto. "Ho bisogno del tuo aiuto", dice. Chi diavolo è? E cosa vuole così tanto da strisciare fuori da un sacco per cadaveri?],
    [Gestisci una clinica clandestina. Solo contanti. Niente domande. Stasera stai preparando il solito ordine—sacche di sangue, refrigerate, pronte per il ritiro. Apri la porta aspettandoti il contatto abituale. Invece, c'è un distintivo dell'FSB. Inizia a fare domande. Cosa gli dici?],
    [Il tuo amico è ossessionato da questa ragazza. Parla di lei costantemente. Non sta zitto. Ma sta di merda—occhi infossati, pallido, come se lei lo stesse prosciugando. Sta per perdere il lavoro. Il suo appartamento è un disastro. Cosa ti convince ad affrontarlo? E sai che tipo di vampiro ha i suoi artigli su di lui—o stai per scoprirlo nel modo peggiore?],
    [Vai in chiesa come fai sempre. Padre Martin non è all'altare. Lo trovi nella stanza sul retro con un uomo che impugna un fucile d'assalto e una spada—una vera spada lunga medievale. Hanno bisogno del tuo aiuto per cacciare qualcosa. Dicono di non avere altra scelta che chiedertelo. Cosa stanno cacciando? E perché te?],
    [Stai scontando la tua pena quando le luci saltano. Urla. Spari. Qualcosa squarcia il blocco celle come una palla da demolizione, dirigendosi dritto verso un prigioniero. Vedi succedere qualcosa che nessuna persona razionale crederebbe. Chi è il prigioniero? Cosa lo ha fatto evadere? E qual è la tua mossa?],
    [I dottori ti danno settimane. Forse giorni. È successo così in fretta. Stai dicendo addio a qualcuno che ami quando svieni. Ti svegli nell'oscurità, la gola che brucia con una sete così feroce che è agonia. Loro sono lì con te. "Non morirai", sussurrano. Ma non sei più vivo neanche tu. Perché ti hanno trasformato? E come vivi con ciò che sei diventato?],
    [Le dai la caccia da mesi. Anni, forse. Ora l'hai finalmente rintracciata nella Città. Ma stai finendo il tempo. Se non la prendi presto, succede qualcosa di catastrofico. Cos'è? Perchè sei così di fretta? E cosa succede se fallisci?],
    [La tua magia si è risvegliata male. Qualcuno che ami è in ospedale—o peggio. Una strega ha visto cosa hai fatto. Ti prende da parte, ti avverte dell'Unione della Magia. "Ti troveranno", dice. "Lascia che ti aiuti a sparire". Ti fidi di lei? E qual'è il tuo potere?],
    [Sei dell'FSB. Il tuo partner ti trascina in una tromba delle scale, sussurra qualcosa su una talpa. Poi svanisce. Niente chiamate. Nessuna traccia. Cosa ti ha detto? E cosa hai intenzione di farci?],
    [Sei un mago dell'Unione mandato a fare da mentore a un ragazzino il cui potere è appena emerso. Ora sei su un tetto alle 3 del mattino, cercando di convincerlo a non buttarsi. Letteralmente: vuole saltare. Perché? Cosa ha fatto la sua magia? E puoi dire qualcosa che lo faccia tornare indietro?],
    [Qualcuno ti ha chiamato per un'infestazione. Ti presenti. Le persone che ti hanno chiamato sono morte. Fresche. Ancora calde. Il fantasma è ancora qui. E sa che stai arrivando.],
    [Stai ballando, strafatto, perso nella musica e nel calore del corpo di qualcuno contro il tuo. Non ricordi di aver preso nulla. Il basso scende. Il tempo rallenta. Cogli un luccichio d'argento nei suoi occhi—la sua pelle luccicante, troppo perfetta. Ti lasci andare. Ore dopo, ti svegli in un letto strano. La tua compagnia? Coltello nel cuore. Qualcuno lo sta estraendo, dicendoti di stare calmo. Che cazzo è successo? E chi sta tenendo il coltello?],
    [Bersagli di alto profilo stanno morendo. Politici. CEO. I loro corpi esplodono dall'interno, lasciando nient'altro che sangue e il loro cuore intatto sul pavimento, ancora battente. Finché qualcuno non lo guarda. Poi si ferma. Sei quello che chiamano per questo genere di cose. In cosa ti stai cacciando?],
    [Hai visto il tuo partner venire fatto a pezzi da un vampiro. L'hai detto al capitano. Pensa che tu stia perdendo la testa, ti vuole in congedo psichiatrico. Sai cosa hai visto. Hai una pista. Quindi sbatti il distintivo e la pistola sulla sua scrivania e te ne vai. Fuori, qualcuno sta aspettando. Offre il suo aiuto. Chi è? E cosa vuole in cambio?],
    [Si dice che ci sia una strega che può rendere i mostri di nuovo mortali. Curare il vampirismo. Togliere la licantropia. Portare indietro l'orologio. Come ne hai sentito parlare? E perché sei abbastanza disperato da crederci?],
    [La Guardia Nazionale ha bloccato la Città. Posti di blocco. Coprifuoco. Nessuno entra o esce. Elicotteri sopra la testa. Non dicono perché. Eri già dentro quando è successo? O sei stato mandato dentro per occuparti di qualunque cosa sia libera?],
    [Un'esplosione nelle fogne ha fatto crollare mezzo isolato. I poliziotti si stanno equipaggiando per entrare. Sai cosa c'è laggiù. O pensi di saperlo. Cosa stanno per trovare? E perché ti terrorizza?],
    [Il tuo maestro ti ha mandato a recuperare un antico artefatto. È in città, nelle mani di qualcuno. Chi ce l'ha? Come hai intenzione di prenderlo? E cosa succede se fallisci?],
    [La gente si sta riversando nella cattedrale. Dicono che la Vergine Maria sia apparsa nella navata, piangendo sangue. Tu ne sai di più. È uno spettro—e uno pericoloso. Cosa vuole? E come lo fermi prima che qualcuno venga ucciso?],
    [Persone non collegate—età, background, vite diverse—stanno entrando nello stesso magazzino e facendola finita. Impiccagione. Overdose. Proiettile. I poliziotti pensano che sia una setta suicida. Tu sai che è qualcosa di peggio. Cosa li sta costringendo? Come sono collegati? E perché ti importa?],
    [Le locuste sciamano per le strade, oscurando il cielo. La gente urla dell'apocalisse. Ma questa non è la fine del mondo. È un avvertimento. Un presagio. Qualcosa sta arrivando. Cosa? Come lo sai? E cosa puoi fare per fermarlo?],
    [La biblioteca pubblica è bruciata fino alle fondamenta. Tranne una sezione—intatta, incontaminata, circondata dalla cenere. Qualcuno sta andando lì. Qualcun altro sta cercando di fermarli. Da che parte stai? E cosa c'è in quella sezione per cui vale la pena uccidere?],
    [La chiamano la Seconda Venuta. I Cavalieri della Croce ne sanno di più. Non è Cristo. Cos'è? Cosa vuole? E come lo fermi?],
    [Sei venuto in Città per riportare una reliquia al suo luogo di riposo. Sei stato vittima di un'imboscata nel momento in cui sei arrivato. Lasciato sanguinante in un vicolo, la reliquia sparita. Chi sapeva che stavi arrivando? E come hai intenzione di finire il lavoro?],
    [Si fidavano di te per proteggere qualcuno di molto importante, ma ti sei distratto per un secondo ed è sparito. Chi era? Perché aveva bisogno di protezione? E come sistemi le cose?],
    [Il sole tramonta. La luna sorge rossa. L'intero cielo sanguina cremisi: La Luna di Sangue. Come deforma la città? Cosa ti fa?],
    [Una donna ti trova. Disperata. Tremante. Suo marito—scomparso da due settimane. La polizia non aiuterà. Perché viene da te? E cosa ti fa dire di sì?],
  ),
  [Seme d'Avventura],
)
