#import "../../template.typ": keep_together, rpg_table, table_d66, table_d66_double

#pagebreak()
=== Locations

==== Type of Place

#table_d66_double(
  (
    [Mansion],
    [Pub/Bar],
    [Apartment],
    [House],
    [Hotel],
    [Restaurant],
    [Library],
    [Cemetery],
    [Art Gallery],
    [Parking Garage],
    [City Hall],
    [Coffee Shop],
    [Psychic Parlor],
    [Drug Market],
    [Prison],
    [Rooftop],
    [Square],
    [Night Market],
    [Cottage],
    [Cabin],
    [Funeral Home],
    [University Building],
    [Subway Station],
    [Park],
    [Museum],
    [Convenience Store],
    [Diner],
    [Amusement Park],
    [Theater],
    [Movie Theater],
    [Antique Shop],
    [Gas Station],
    [Food Stand],
    [Homeless Shelter],
    [Brothel],
    [Adult Club],
  ),
  [Place],
)

#pagebreak()
==== Place Quirk

#table_d66_double(
  (
    [Gloomy],
    [Bustling],
    [Shadowy],
    [Serene],
    [Dilapidated],
    [Vibrant],
    [Haunting],
    [Cozy],
    [Foreboding],
    [Tranquil],
    [Desolate],
    [Lively],
    [Ancient],
    [Bright],
    [Crumbling],
    [Peaceful],
    [Eerie],
    [Modern],
    [Claustrophobic],
    [Spacious],
    [Inviting],
    [Dark],
    [Colorful],
    [Damp],
    [Clean],
    [Sinister],
    [Ordinary],
    [Rotting],
    [Sleek],
    [Isolated],
    [Welcoming],
    [Blighted],
    [Busy],
    [Stark],
    [Safe],
    [Familiar],
  ),
  [Quirk],
)

#pagebreak()
==== Secret Location Inside

#table_d66(
  (
    [Vault],
    [Vault],
    [Hideout],
    [Hideout],
    [Library],
    [Library],
    [Art Room],
    [Art Room],
    [Relic Room],
    [Relic Room],
    [Shrine],
    [Shrine],
    [Conference Room],
    [Conference Room],
    [Passage to elsewhere],
    [Passage to elsewhere],
    [Tomb],
    [Tomb],
    [Ritual Chamber],
    [Ritual Chamber],
    [Torture Chamber],
    [Torture Chamber],
    [Lab],
    [Lab],
    [Observatory],
    [Observatory],
    [Crypt],
    [Crypt],
    [Temple],
    [Temple],
    [Prison],
    [Prison],
    [Secret Armory],
    [Hidden Sanctuary],
    [Forbidden Archive],
    [Blood Chamber],
  ),
  [Secret Room],
)

#pagebreak()
==== Neighborhood Known For…

#table_d66_double(
  (
    [Nightlife],
    [Industrial parks],
    [Gentrified housing],
    [Touristic beaches],
    [Quiet suburbs],
    [Natural parks],
    [Crime],
    [Poverty],
    [Vacant houses],
    [Cemeteries],
    [Woods],
    [Pond],
    [Food stalls],
    [Business centers],
    [Universitiy],
    [Shopping malls],
    [Bus terminals],
    [Construction zones],
    [Museums],
    [Hotels],
    [Slums],
    [Abandoned factories],
    [Public squares],
    [Power stations],
    [Skyscrapers],
    [Rail stations],
    [Community centers],
    [Warehouses],
    [Government buildings],
    [Historic buildings],
    [Red light district],
    [Financial district],
    [Arts district],
    [Beach],
    [Underground tunnels],
    [Supernatural activity],
  ),
  [Known For],
)
