#import "../template.typ": rpg_table

== Characters

In Bloodstained Fangs, you step into the shoes of *vampires, lycantropes, witches*, trying to hold onto your humanity while *living in the shadows*. You may be a *neonate Vampire*, a *travelling vampire hunter*, or a *cursed werewolf*. Or maybe you are a newly initiate member of an organization of *Vampire Hunters*, or a recently promoted secret agent just transferred to the *Paranormal Investigations Division*.

Each character carries *the burden of their condition (and/or knowledge), powerful skills and abilities, and deadly natural enemies*. Some may find *power, allies, and peace*, while others risk *falling into darkness, losing their humanity and becoming entirely monsters*. Even those who hunt the monsters for the greater good are at risk of becoming one of them.

Your journey will be one of *mystery, horror, and thrill*, where each step brings you *deeper in the underworld*. Will you reach safety and freedom, or will your story end in tragedy?

=== Everything is a Character!

In _Bloodstained Fangs_ Non-Playing Characters (NPCs), Foes, Organizations, Monsters, and even relevant objects like vehicles are characters too!

Your Protagonist is described by some fixed traits:

- *Name*: The name should be iconic and consistent with the tone and setting of the story.
- *Concept*: A concise description of the character's profession, background, and abilities. The best are adjective-name pairings, like _"Venturous Smuggler"_ or _"Child Prodigy"_.
- *Skills* (x2): Abilities not necessarily character-specific but not characteristics common to all. _"Smart"_ is not a skill, _"Engine Whisperer"_ is.
- *Frailty*: Something that could potentially get in the way of the character, either physically, mentally, or socially.
- *Gear* (x2): Particular equipment supplied to the character in coherence with the setting. Everyday items are taken for granted and do not fall under this trait.
- *Goal*: The long-term objective.
- *Motive*: What drives the pursuit of the goal.
- *Nemesis*: A person or organization that hinders the protagonist. It can emerge during the first game sessions, it may or may or not be the direct antagonist of the story, ready to appear to make life even more difficult
- *Luck*: The measure of a character's ability to avoid ill fortune or an inauspicious outcome. It applies only in Conflicts and automatically recharges when they end. Luck starts and caps at 6.

These *traits* are described by *tags*, descriptive words or phrases that can identify anything in the game world. Even the *details* of the environment in which the action moves and *conditions* (physical or mental) of the characters are tags.

*They are qualitative representations. They are not quantitative measures.*

== Character Traits

You can use these traits to create a character on the fly, mix them, or just use them as inspiration.

=== Concepts

#rpg_table(
  columns: 7,
  [2D6],
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [1],
  [Hardboiled Vampire Hunter],
  [Struggling Neonate Vampire],
  [Moon Order Acolyte],
  [Reckless Young Lycantrope],
  [Alpha Pack Leader Werewolf],
  [Vamp Motorcycle Club Sergeant],

  [2],
  [Occult Lore Hunter],
  [Concerned Historian],
  [Determined Detective],
  [Undercover Federal Agent],
  [Nomad Wizard of the Moon],
  [Desperate Drug Addict Turned Vampire],

  [3],
  [Witch Coven Leader],
  [Ancient Experienced Wizard],
  [Nightlife Dweller],
  [Amateur Ghostbuster],
  [Vatican Exorcist],
  [Eccentric Wealthy Hobbyst],

  [4],
  [Experienced Ghostbuster],
  [Federal Agent],
  [Lost Tourist],
  [Rebellious Soul Vampire],
  [Silver Weapon Smith],
  [Audacious Relic Hunter],

  [5],
  [Accomplished Ghost Medium],
  [Unconventional Exiled Scientist],
  [Underworld Diplomat],
  [Knucklehead Gangster],
  [Occult-curious Cunning Gangster],
  [Occult-dealing Underworld Smuggler],

  [6],
  [Talented Fortune Teller],
  [Haunted Fugitive],
  [Accomplished Elder Vampire],
  [Werewolf Pack Newcomer],
  [Underworld Assassin],
  [High Profile Politician With Supernatural Ties],
)

=== Skills

#rpg_table(
  columns: 7,
  [2D6],
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [1],
  [Ancient Lore],
  [Street Fight],
  [Guns],
  [Explosives],
  [Alchemy],
  [Blood Magic],
  [2],
  [Moon Magic],
  [Prescience],
  [Hacking],
  [Bureaucracy],
  [Law],
  [Tracking],
  [3],
  [Electronics],
  [Espionage],
  [Biology],
  [Martial arts],
  [Blood Charm],
  [Telekinesis],
  [4],
  [Curses],
  [Exorcism],
  [Diplomacy],
  [Archeology],
  [Parkour],
  [Seduction],
  [5],
  [Intimidation],
  [Chemistry],
  [Stealth],
  [First Aid],
  [Safe cracking],
  [Guerrilla Tactics],
  [6],
  [Safe cracking],
  [Ghost Communion],
  [Lockpicking],
  [Necromancy],
  [Talking with animals],
  [Climbing],
)

=== Frailties

#rpg_table(
  columns: 7,
  [2D6],
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [1],
  [Strong Faith],
  [Scared of violence],
  [Guillible],
  [Fear of darkness],
  [Fear of hurting mortals],
  [Mortal loved one],

  [2],
  [Wife/Husband],
  [Angered mentor],
  [Fierce Ideology],
  [White knight attitude],
  [Cursed limb],
  [Death curse],
  [3],
  [Must uphold social justice],
  [Authoritarian],
  [Disregard for authorities],
  [Anarch],
  [Self sabotage],
  [Self hate],

  [4],
  [Hunted],
  [Ghoul],
  [Compulsive truth-teller],
  [Obsessed with ancient relics],
  [Chronic insomnia],
  [Wanted by the law],

  [5],
  [Terrified of fire],
  [Childhood trauma],
  [Terrified of drowning],
  [Can't swim],
  [Rage issues],
  [Drug addict],
  [6],
  [Alcoholic],
  [Debt ridden],
  [Rich and famous],
  [Limp / Bad leg],
  [Strong accent],
  [Sickly and weak],
)

=== Gear

#rpg_table(
  columns: 7,
  [2D6],
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [1],
  [Silenced Pistol],
  [Silver Dagger],
  [Faith Symbol],
  [Bone Wand],
  [Moon Stone],
  [Arcane Tome],
  [2],
  [Ring of Telekinetic Force],
  [Pen that can only write true things],
  [Vial with Vampire Blood],
  [Cursed Tome],
  [Police Badge],
  [Bottle of Holy Water],

  [3],
  [Magic Detector],
  [Key that opens almost any lock],
  [Invisibility cloak],
  [UV Flashlight],
  [Ghost Detector],
  [Tactical Vest],

  [4],
  [Shotgun],
  [Vampire Fang Necklace],
  [Ancestor's Locket],
  [Fake ID],
  [Sun lamp],
  [Motorcycle],
  [5],
  [Ancient Katana],
  [Radio Jammer],
  [Lockpicks],
  [Sketched Underworld Map],
  [Magical Broom],
  [Magic Shield],
  [6],
  [Throwing Knives],
  [Crossbow],
  [Blood bag],
  [Night Vision Goggles],
  [Universal Screwdriver],
  [Small Caliber Gun],
)

#pagebreak()

=== Names

==== Female Names

#rpg_table(
  columns: 7,
  [2D6],
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [1],
  [Amber],
  [Isabella],
  [Selene],
  [Victoria],
  [Zara],
  [Rosemary],
  [2],
  [Willow],
  [Bianca],
  [Lilith],
  [Scarlet],
  [Zoey],
  [Rebecca],
  [3],
  [Violet],
  [Celeste],
  [Delilah],
  [Judith],
  [Prudence],
  [Sarah],
  [4],
  [Ember],
  [Chloe],
  [Vanessa],
  [Morgana],
  [Jasmine],
  [Aurora],
  [5],
  [Luna],
  [Iside],
  [Ophelia],
  [Isadora],
  [Morgana],
  [Tamara],
  [6],
  [Thea],
  [Theodora],
  [Hannah],
  [Jessica],
  [Juliet],
  [Meave],
)

==== Male Names

#rpg_table(
  columns: 7,
  [2D6],
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [1],
  [Damien],
  [Elliot],
  [Mark],
  [Marcus],
  [Vincent],
  [Ezekiel],
  [2],
  [Adrian],
  [Xavier],
  [Jacob],
  [Michael],
  [Kieran],
  [Lucian],
  [3],
  [Silas],
  [Zachary],
  [Cassian],
  [Asher],
  [Alex],
  [Felix],
  [4],
  [Nathan],
  [Eric],
  [Cole],
  [Kael],
  [Vito],
  [Daniel],
  [5],
  [Diego],
  [Edward],
  [Dominique],
  [Luca],
  [Paul],
  [Liam],
  [6],
  [Bob],
  [Andrew],
  [Samuel],
  [Dean],
  [Dorian],
  [Matt],
)

==== Surnames

#rpg_table(
  columns: 7,
  [2D6],
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [1],
  [Cross],
  [Caine],
  [Frost],
  [Bloodworth],
  [Carmichael],
  [Ravenscroft],
  [2],
  [Blackwood],
  [Night],
  [Irons],
  [Bishop],
  [Evans],
  [Crowley],
  [3],
  [Christie],
  [Kennedy],
  [Sterling],
  [Mercer],
  [Wolf],
  [Ashworth],
  [4],
  [Lancaster],
  [Darkmoon],
  [Flint],
  [Winters],
  [Graves],
  [Cross],
  [5],
  [Mulder],
  [Skully],
  [Stark],
  [Black],
  [White],
  [Reed],
  [6],
  [Moore],
  [Cullen],
  [Winchester],
  [Alliwell],
  [Bell],
  [Smith],
)

#pagebreak()
=== Nicknames

#rpg_table(
  columns: 7,
  [2D6],
  [1],
  [2],
  [3],
  [4],
  [5],
  [6],
  [1],
  [Shadow],
  [Trinity],
  [Winter],
  [Nyx],
  [Phoenix],
  [Midnight],
  [2],
  [Dusk],
  [Sunrise],
  [Sunset],
  [Twilight],
  [Blade],
  [Edge],
  [3],
  [Needle],
  [Thorn],
  [Bullet],
  [Slash],
  [Raven],
  [Hound],
  [4],
  [Nightshade],
  [Leech],
  [Cannon],
  [Atom],
  [Skull],
  [Ghost],
  [5],
  [Shadow],
  [Wraith],
  [Hex],
  [Stalker],
  [Stray],
  [Silence],
  [6],
  [Reaper],
  [The Hanged],
  [Ripple],
  [Master Mirror],
  [Duke],
  [Crimson],
)
